### ISSUE TITLE
Add libnvme.so.1 to omicron zones

### ISSUE THREAD

**Issue by sunshowers** [oxidecomputer/helios-omicron-brand#15]
We discovered today, post oxidecomputer/omicron#5158, that we need to add `libnvme.so` and `libnvme.so.1` to all our omicron zones. This task tracks adding them.

For now, they're available at `/system/usr/lib/amd64`, and can be used by copying them to a new temp dir e.g. `foobar`, and setting `LD_LIBRARY_PATH=/tmp/foobar` in the environment.

**Comment by jclulow** [comment]
Are you talking about in the product ramdisk or on an engineering workstation?

**Comment by sunshowers** [comment]
Post https://github.com/oxidecomputer/omicron/pull/5158, I believe that all our official omicron-built binaries are going to depend on libnvme.so.1 -- so it would need to be in the product ramdisk. (See discussion [starting here in #oxide-control-plane](https://matrix.to/#/!YNYPOVxjAUeXksTcRj:oxide.computer/$gEnms4RwEkJEF49ODQWjTdNgTu8i-kUUYTCdsU-5v0Q?via=oxide.computer&via=unix.house&via=matrix.org) for more)

**Comment by papertigers** [comment]
It turns out that `libnvme.so.1` is [marked as a global zone only library](https://github.com/illumos/illumos-gate/blob/96a443fb7853ca3d0303049d396409479475a9c7/usr/src/pkg/manifests/driver-storage-nvme.p5m#L26) and for good reason.

@jgallagher fixed this by splitting out the sled-hardware types into their own crate in https://github.com/oxidecomputer/omicron/pull/5245

Additionally I have opened https://github.com/oxidecomputer/omicron/pull/5259 in attempt to catch these things sooner as apart of buildomat test runs.
